ci:
  # This section tells pre-commit.ci to create a pull request
  # to update the linter version tag every month.
  autoupdate_schedule: monthly

  # If you have other Ansible collection dependencies (requirements.yml),
  # `pre-commit.ci` will not be able to install them because it runs in offline mode.
  # Uncomment to skip the ansible-lint hook if needed.
  # skip:
  #   - ansible-lint

repos:
- repo: https://github.com/ansible/ansible-lint  # Official repo for ansible-lint
  rev: v5.0.0  # Replace with the latest release tag from https://github.com/ansible/ansible-lint/releases/
  hooks:
    - id: ansible-lint
      # Uncomment the following if you need the full Ansible community bundle instead of ansible-core:
      # additional_dependencies:
      #   - ansible
