name: Ansible Lint and Check

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      - 'roles/**'
      - 'post_build.yml'
      
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - 'roles/**'
      - 'post_build.yml'

jobs:
  lint:
    name: Lint Ansible Playbooks
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # You can use another Python version if needed

      # Install Ansible, Ansible Lint, and yamllint
      - name: Install dependencies
        run: |
          pip install ansible ansible-lint yamllint

      # Run Ansible Lint with custom configuration and --fix
      - name: Run Ansible Lint
        run: |
          ansible-lint -c .ansible-lint-config.yml --fix .  # Modify with actual path if needed

      # Run yamllint (for YAML syntax validation)
      - name: Run yamllint
        run: |
          yamllint .  # This checks all YAML files in the repository

      # Check if any files were modified by ansible-lint fixes
      - name: Check if files were fixed
        id: check_files
        run: |
          git diff --exit-code
          if [ $? -eq 1 ]; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      # Commit and push changes if any fixes were applied
      - name: Commit fixed files
        if: ${{ env.changed == 'true' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Fix ansible-lint issues"
          git push
