# Variables
ANSIBLE_LINT_CONFIG = .ansible-lint
ANSIBLE_LINT_IGNORE = .ansible-lint-ignore

# Default target
all: linting-errors

# Auto-fix linting errors
auto-fix-linting:
	@echo "Running ansible-lint with --fix to auto-fix linting errors..."
	@ansible-lint --fix

# Get linting errors
linting-errors:
	@echo "Running ansible-lint to get linting errors..."
	@ansible-lint

# Create .ansible-lint file with default configuration
create-ansible-lint-config:
	@echo "Creating .ansible-lint file with default configuration..."
	@echo "skip_list: []" > $(ANSIBLE_LINT_CONFIG)
	@echo "fail_on_warning: False" >> $(ANSIBLE_LINT_CONFIG)

# Configure .ansible-lint-ignore file with empty ignore list
create-ansible-lint-ignore:
	@echo "Creating .ansible-lint-ignore file with an empty ignore list..."
	@touch $(ANSIBLE_LINT_IGNORE)


