# Correct (package module inside tasks)
---
- name: Install Apache
  hosts: all
  tasks:
    - name: Install Apache package
      ansible.builtin.package:
        name: httpd
        state: present
        