---
- hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: "Setup ansible facts"
    include_tasks: common_build.yml

  - name: "Include RHEL tasks"
    include_tasks: setup_rhel.yml
    when: ansible_distribution == "RedHat"
  
  - name: "Include OL tasks"
    include_tasks: setup_ol.yml
    when: ansible_distribution == "OracleLinux"

  - name: "Include Ubuntu tasks"
    include_tasks: setup_ubuntu.yml
    when: ansible_distribution == "Ubuntu"