---
name: Ansible Lint and Check

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      - 'roles/**'
      - 'post_build.yml'
      
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - 'roles/**'
      - 'post_build.yml'

jobs:
  lint:
    name: Lint Ansible Playbooks
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

    # Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # You can use another Python version if needed

    # Install Ansible, Ansible Lint,
      - name: Install dependencies
        run: |
          pip install ansible ansible-lint

    # Run Ansible Lint with custom configuration and --fix
      - name: Run Ansible Lint
        run: |
          ansible-lint -c .ansible-lint-config.yml --fix . > lint_output.txt  # Modify with actual path if needed

       