name: ansible-lint

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      - 'roles/**'
      - 'post_build.yml'
      
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - 'roles/**'
      - 'post_build.yml'

jobs:
  build:
    name: Ansible Lint  # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Adjust the version to match your needs

      - name: Install ansible-lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "--config .ansible-lint.yml"  # Example of passing an argument to ansible-lint
          setup_python: "true"
          working_directory: ""  # If your playbooks are in a specific folder, specify it here
          requirements_file: "requirements.yml"  # If you have dependencies, specify the requirements file
