name: "SonarQube Scan"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
permissions: read-all

jobs:
  scan:
    name: "SonarQube Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "SonarQube Scan"
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: https://sonarqube.gsk.com
        with:
          args: -Dsonar.projectKey=${{ vars.SONARQUBE_PROJECT_KEY }} -Dsonar.qualitygate.wait=true
